
// export const editOptions = [
//     {
//         "template_id": 149880,
//         "image_url": "https://files.cdn.printful.com/m/g18500/medium/ghost/front/05_gildan18500_ghost_front_base_whitebg.png?v=1692703516",
//         "background_url": null,
//         "background_color": "#0b0b0b",
//         "printfile_id": 139,
//         "template_width": 3000,
//         "template_height": 3000,
//         "print_area_width": 1136,
//         "print_area_height": 1136,
//         "print_area_top": 651,
//         "print_area_left": 927,
//         "placement":'Front',
//         "is_template_on_front": true,
//         "orientation": "any"
//     },
//     {
//         "template_id": 149893,
//         "image_url": "https://files.cdn.printful.com/m/g18500/medium/ghost/back/05_gildan18500_ghost_back_base_whitebg.png?v=1692703516",
//         "background_url": null,
//         "background_color": "#0b0b0b",
//         "printfile_id": 1,
//         "placement":'Back',
//         "template_width": 3000,
//         "template_height": 3000,
//         "print_area_width": 1095,
//         "print_area_height": 1460,
//         "print_area_top": 493,
//         "print_area_left": 919,
//         "is_template_on_front": true,
//         "orientation": "any"
//     },
//     {
//         "template_id": 3618,
//         "image_url": "https://files.cdn.printful.com/m/templates/medium/outside_label_3x3.png?v=1692703516",
//         "background_url": null,
//         "background_color": "#0b0b0b",
//         "printfile_id": 90,
//         "template_width": 560,
//         "template_height": 560,
//         "placement":'Label Inside',
//         "print_area_width": 288,
//         "print_area_height": 288,
//         "print_area_top": 187,
//         "print_area_left": 137,
//         "is_template_on_front": false,
//         "orientation": "any"
//     },
//     {
//         "template_id": 149919,
//         "image_url": "https://files.cdn.printful.com/m/g18500/medium/ghost/right/05_gildan18500_ghost_right_base_whitebg.png?v=1692703516",
//         "background_url": null,
//         "background_color": "#0b0b0b",
//         "printfile_id": 147,
//         "template_width": 3000,
//         "template_height": 3000,
//         "print_area_width": 277,
//         "print_area_height": 1104,
//         "print_area_top": 1065,
//         "print_area_left": 1318,
//         "placement":'Left Hand',
//         "is_template_on_front": true,
//         "orientation": "any"
//     },
// ]

export const editOptions = [
    
        {
            "background_color": null,
            "background_url": null,
            "image_url": "https://files.cdn.printful.com/m/Denim_Tshirt_Husky_CA6689/medium/mens/front/embroidery/front/05_HuskyTeeMan_front_black_base_whitebg.png?v=1691997846",
            "is_template_on_front": false,
            "orientation": "any",
            "print_area_height": 394,
            "print_area_left": 1192,
            "print_area_top": 1083,
            "print_area_width": 394,
            "placement":'Front Right Chest',
            "printfile_id": 136,
            "template_height": 2000,
            "template_id": 56281,
            "template_width": 2000
        },
        {
            "background_color": null,
            "background_url": null,
            "image_url": "https://files.cdn.printful.com/m/Denim_Tshirt_Husky_CA6689/medium/mens/front/embroidery/front/05_HuskyTeeMan_front_black_base_whitebg.png?v=1691997846",
            "is_template_on_front": false,
            "orientation": "any",
            "print_area_height": 394,
            "print_area_left": 814,
            "print_area_top": 1090,
            "placement":'Front Center Chest',
            "print_area_width": 394,
            "printfile_id": 136,
            "template_height": 2000,
            "template_id": 56285,
            "template_width": 2000
        },
        {
            "background_color": null,
            "background_url": null,
            "image_url": "https://files.cdn.printful.com/m/Denim_Tshirt_Husky_CA6689/medium/mens/front/embroidery/front/05_HuskyTeeMan_front_black_base_whitebg.png?v=1691997846",
            "is_template_on_front": false,
            "orientation": "any",
            "print_area_height": 593,
            "print_area_left": 518,
            "print_area_top": 1090,
            "placement":'Front Top Chest',
            "print_area_width": 987,
            "printfile_id": 222,
            "template_height": 2000,
            "template_id": 118737,
            "template_width": 2000
        },
        {
            "background_color": "#323236",
            "background_url": null,
            "image_url": "https://files.cdn.printful.com/m/templates/medium/inside_label__3x3.png?v=1691997846",
            "is_template_on_front": true,
            "orientation": "any",
            "print_area_height": 288,
            "print_area_left": 137,
            "print_area_top": 187,
            "placement":'Inside label',
            "print_area_width": 288,
            "printfile_id": 71,
            "template_height": 560,
            "template_id": 138379,
            "template_width": 560
        },
        {
            "background_color": null,
            "background_url": null,
            "image_url": "https://files.cdn.printful.com/m/Denim_Tshirt_Husky_CA6689/medium/mens/left/zoomed/05_HuskyTee_Man_left_black_base_whitebg.png?v=1691997846",
            "is_template_on_front": false,
            "orientation": "any",
            "print_area_height": 252,
            "print_area_left": 406,
            "print_area_top": 440,
            "placement":'Sleeve left',
            "print_area_width": 167,
            "printfile_id": 396,
            "template_height": 1000,
            "template_id": 142196,
            "template_width": 1000
        },
        {
            "background_color": null,
            "background_url": null,
            "image_url": "https://files.cdn.printful.com/m/Denim_Tshirt_Husky_CA6689/medium/mens/right/zoomed/05_HuskyTee_Man_right_black_base_whitebg.png?v=1691997846",
            "is_template_on_front": false,
            "orientation": "any",
            "print_area_height": 250,
            "print_area_left": 323,
            "placement":'Sleeve Right',
            "print_area_top": 444,
            "print_area_width": 166,
            "printfile_id": 396,
            "template_height": 1000,
            "template_id": 142204,
            "template_width": 1000
        },
       
   
]



// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/12_mini.png?v=1693914443",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185620,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/12_mini.png?v=1693914443",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185621,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/upload/api-template/1c/1c77b7db9ed08873226af5d1060ca51d?v=1689330043",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185624,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/upload/api-template/1c/1c77b7db9ed08873226af5d1060ca51d?v=1689330043",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185625,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/12_pro.png?v=1693914494",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185628,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/12_pro.png?v=1693914494",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185629,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/12_promax.png?v=1693914522",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185632,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/12_promax.png?v=1693914522",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185633,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/13_mini.png?v=1693914551",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185636,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/13_mini.png?v=1693914551",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185637,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/upload/api-template/a2/a21c35cfcb28715d7bf9839035caa41b?v=1689328902",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185640,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/upload/api-template/a2/a21c35cfcb28715d7bf9839035caa41b?v=1689328902",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185641,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/13_pro.png?v=1693914602",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185644,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/13_pro.png?v=1693914602",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185645,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/13_promax.png?v=1693914633",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185648,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/13_promax.png?v=1693914633",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185649,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/upload/api-template/4a/4af4bf17fe86603378d76022407fd3e8?v=1689328200",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185652,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/upload/api-template/4a/4af4bf17fe86603378d76022407fd3e8?v=1689328200",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185653,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/14_plus.png?v=1693914686",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185656,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/14_plus.png?v=1693914686",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185657,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/14_pro.png?v=1693914718",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185660,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/14_pro.png?v=1693914718",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185661,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/14_promax.png?v=1693914746",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185664,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/14_promax.png?v=1693914746",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 185665,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/upload/api-template/98/98d40526b0f5078b318aced8b6c7a865?v=1693897328",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 208872,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/upload/api-template/98/98d40526b0f5078b318aced8b6c7a865?v=1693897328",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 208873,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/14_plus.png?v=1693914795",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 208902,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/14_plus.png?v=1693914795",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 208903,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/14_pro.png?v=1693914813",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 208932,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/14_pro.png?v=1693914813",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 208933,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/14_promax.png?v=1693914847",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 208962,
//     "template_width": 728
// },
// {
//     "background_color": "#ffffff",
//     "background_url": null,
//     "image_url": "https://files.cdn.printful.com/m/snap_case_for_iphone/medium/template3/14_promax.png?v=1693914847",
//     "is_template_on_front": true,
//     "orientation": "any",
//     "print_area_height": 528,
//     "print_area_left": 205,
//     "print_area_top": 100,
//     "print_area_width": 318,
//     "printfile_id": 438,
//     "template_height": 728,
//     "template_id": 208963,
//     "template_width": 728
// }