name: wishgenie-frontend-service-actions

on:
  push:
    branches:
      - main/stop

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: 528157142847.dkr.ecr.ap-south-1.amazonaws.com
  IMAGE_NAME: wishgenie-frontend

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build Docker image
      run: |
        docker build -t $ECR_REGISTRY/onebillionideas:wishgenie-frontend .     
    - name: Push Docker image to ECR
      run: |
        docker push $ECR_REGISTRY/onebillionideas:wishgenie-frontend
        
  deploy-Container:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: SSH into EC2 instance and deploy Docker container
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_IP }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.EC2_PASSWORD }}
        script: |
            docker pull $ECR_REGISTRY/onebillionideas:wishgenie-frontend
            docker stop wg-frontend-container || true
            docker rm wg-frontend-container || true
            docker run -d --name wg-frontend-container -p 3000:3000 528157142847.dkr.ecr.ap-south-1.amazonaws.com/onebillionideas:wishgenie-frontend       
