name: wishgenie-frontend-service-actions

on:
  push:
    branches:
      - main/stop

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: 528157142847.dkr.ecr.ap-south-1.amazonaws.com
  IMAGE_NAME: wishgenie-frontend

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: SSH into EC2 instance and deploy Docker container
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_IP }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.EC2_PASSWORD }}
        script: |
            pwd
            cd wg-work-directory
            rm -rf wg-frontend
            git clone git@github.com:YashOBI/wg-frontend.git
            cd wg-frontend
            git pull --all
            docker build -t wishgenie:ui .     
            docker stop wg-frontend-containe-manual || true
            docker rm wg-frontend-containe-manual || true
            docker run -d --name  wg-frontend-containe-manual -p 3000:3000 wishgenie:ui   


name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v3
  env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
